# part 1


How to create an empty and a full NumPy array?

Create a Numpy array filled with all zeros

Create a Numpy array filled with all ones

Flatten a 2d numpy array into 1d array

Reverse a numpy array

Change data type of given numpy array

In [2]:
#1. How to create an empty and a full NumPy array?
import numpy as np
array=np.array([])
print(type(array))

<class 'numpy.ndarray'>


In [5]:
#2. Create a Numpy array filled with all zeros

np.zeros((3,2))

array([[0., 0.],
       [0., 0.],
       [0., 0.]])

In [6]:
#3. Create a Numpy array filled with all ones

np.ones((5,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [21]:
#4. Flatten a 2d numpy array into 1d array

array1=np.arange(0,12,2).reshape((3,-1))
print(array1)
print(array1.flatten())


[[ 0  2]
 [ 4  6]
 [ 8 10]]
[ 0  2  4  6  8 10]


In [29]:
#5.Reverse a numpy array

array1=np.arange(0,12,2).reshape((3,-1))
print("input",array1)
print("output",array1[::1,::-1])

input [[ 0  2]
 [ 4  6]
 [ 8 10]]
output [[ 2  0]
 [ 6  4]
 [10  8]]


In [36]:
#6.Change data type of given numpy array

array1=np.arange(0,12,2).reshape((3,-1))
new_array_dt=np.array(array1,dtype='f')
print(new_array_dt)

[[ 0.  2.]
 [ 4.  6.]
 [ 8. 10.]]


# part 2

Get the maximum value from given matrix

Get the minimum value from given matrix

Find the number of rows and columns of a given matrix using NumPy

Select the elements from a given matrix

Find the sum of values in a matrix

Calculate the sum of the diagonal elements of a NumPy array

Adding and Subtracting Matrices in Python

Ways to add row/columns in numpy array

In [48]:
#1.Get the maximum value from given matrix

array=np.array([[2,3,4,5],[8,9,10,11]])
print(array)
mx=np.max(array,axis=1)
print("max:",mx)

[[ 2  3  4  5]
 [ 8  9 10 11]]
max: [ 5 11]


In [49]:
#2.#1.Get the minimum value from given matrix
array=np.array([[2,3,4,5],[8,9,10,11]])
print(array)
mn=np.min(array,axis=1)
print("min:",mn)

[[ 2  3  4  5]
 [ 8  9 10 11]]
min: [2 8]


In [53]:
#3.Find the number of rows and columns of a given matrix using NumPy

array=np.array([[2,3,4,5],[8,9,10,11]])
n=np.shape(array)
print(n)

(2, 4)


In [74]:
#4 Select the elements from a given matrix

a=np.arange(0,20).reshape(5,-1)
print("array input\n",a)
print("1st row:",a[0])
print("2nd row 3 element:",a[1][2])
print("last row ,last element:",a[-1][-1])
print("2nd element from each row:",a[::1,1])
print("2nd element and 3rd element from every alternate row\n",a[::2,1:3:1])


array input
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]
1st row: [0 1 2 3]
2nd row 3 element: 6
last row ,last element: 19
2nd element from each row: [ 1  5  9 13 17]
2nd element and 3rd element from every alternate row
 [[ 1  2]
 [ 9 10]
 [17 18]]


In [89]:
#5.Find the sum of values in a matrix


array=np.array([[1,2,3],[4,5,6]])
csum=np.sum(array,axis=0)
print("column wise sum:",csum)
rsum=np.sum(array,axis=1)
print("row sum:",rsum)
all_sum=np.sum(array)
print("add all:",all_sum)

column wise sum: [5 7 9]
row sum: [ 6 15]
add all: 21


In [109]:
#6.Calculate the sum of the diagonal elements of a NumPy array


array=np.array([[1,2,3],[4,5,6],[3,3,3]])
pdiag_sum=0
sdiag_sum=0
print(array)
for i in range(0,len(array)):
    pdiag_sum=pdiag_sum+array[i][i]
count=0
for i in range(0,len(array)):
    
    sdiag_sum=sdiag_sum+array[i][-1-count]
    count=count+1
print(pdiag_sum+sdiag_sum)




[[1 2 3]
 [4 5 6]
 [3 3 3]]
20


In [127]:
#7.Adding and Subtracting Matrices in Python

import numpy as np
a=np.array([[1,2,3],[3,3,3]])
b=np.array(([4,7,8],[5,7,8]))
if a.shape==b.shape:
    
    c=a+b
    print(a,b,sep='\n')
    print(c)

    d=a-b
    print(d)
else:
    print("elements cannot be added as matrix rows and columns are not same")


[[1 2 3]
 [3 3 3]]
[[4 7 8]
 [5 7 8]]
[[ 5  9 11]
 [ 8 10 11]]
[[-3 -5 -5]
 [-2 -4 -5]]


In [163]:
#8 Ways to add row/columns in numpy array
import numpy as np
a=np.array([[1,2,3],[3,3,3]])
b=np.array(([4,7,8],[5,7,8]))
a=np.vstack([a,b])
print("vertical stacking:",a)

a=np.array([[1,2,3],[3,3,3]])
b=np.array(([4,7,8],[5,7,8]))
c=np.concatenate((a,b),axis=0)
print("row stacking thru concat:",c)



a=np.array([[1,2,3],[3,3,3]])
b=np.array(([4,7,8],[5,7,8]))
a=np.hstack([a,b])
print("horizontal stacking:",a)

a=np.array([[1,2,3],[3,3,3]])
b=np.array(([4,7,8],[5,7,8]))
c=np.concatenate((a,b),axis=1)
print("column stacking thru concat:",c)

vertical stacking: [[1 2 3]
 [3 3 3]
 [4 7 8]
 [5 7 8]]
row stacking thru concat: [[1 2 3]
 [3 3 3]
 [4 7 8]
 [5 7 8]]
horizontal stacking: [[1 2 3 4 7 8]
 [3 3 3 5 7 8]]
column stacking thru concat: [[1 2 3 4 7 8]
 [3 3 3 5 7 8]]
